
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stamp-app-dev
    env_file:
      - .env
    environment:
      DEBUG: "True"
      ENABLE_HTTPS: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1,app"
      DB_ENGINE: django.db.backends.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 60 mysite.wsgi:application
      "

volumes:
  media_volume:
  static_volume:
