# Generated by Django 6.0.1 on 2026-02-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='spot_icons/'),
        ),
    ]
