# Generated by Django 6.0.1 on 2026-02-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_spot_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='plan_image_path',
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_images/'),
        ),
    ]
