# Generated by Django 6.0.1 on 2026-03-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ssouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='characters/')),
                ('silhouette_image', models.ImageField(upload_to='characters/silhouettes/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='myapp.spot')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
